[features]
seeds = false
skip-lint = false
[programs.localnet]
greet_program = "6fmK5BV525XzSMK8kpPE76Rqb5XuxKG666Qmx7Za9nsN"
[programs.devnet]
greet_program = "6fmK5BV525XzSMK8kpPE76Rqb5XuxKG666Qmx7Za9nsN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/anish/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
